name: GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22] 
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      # - run: pnpm test

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - run: pnpm install --frozen-lockfile
      - run: pnpm run check

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      pages: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 22 (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - run: pnpm install --frozen-lockfile
      - run: pnpm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
